# Generated by Django 4.2 on 2023-04-23 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergame',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 23, 16, 22, 9, 195715)),
        ),
    ]
