# Generated by Django 4.2 on 2023-04-23 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_usergame_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergame',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 23, 16, 24, 55, 378325)),
        ),
    ]
