# Generated by Django 4.2 on 2023-04-25 01:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_usergame_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergame',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 24, 21, 19, 20, 677337)),
        ),
    ]
